# Generated by Django 3.1.6 on 2021-02-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20210204_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
