# Generated by Django 3.1.6 on 2021-02-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_proyecto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='texto_alt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
